import type { Metadata } from "next";
import "./globals.css";

// Components
import Header from "./_components/Header";
import Footer from "./_components/Footer";

// To do: Add OG metadata - LM
export const metadata: Metadata = {
  title: "Stupor Bowl Minneapolis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  const htmlAttributes: { [key: string]: string } = {};

  if (process.env.NEXT_PUBLIC_ENVIRONMENT === "dev") {
    htmlAttributes["data-google-analytics-opt-out"] = ""
  }

  return (
    <html lang="en" {...htmlAttributes}>
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html >
  );
}
